// Before/after table for keyword mode (E3).
//   node tests/compare.mjs            -> prints a summary, writes tests/results/keyword-before-after.md
// "Before" is the widget code from commit fb82fd2 (tests/baseline/), "after" is src/.
// Both are judged by the same checker (tests/check.js) on the same questions.
// The AI-mode table needs a real GPU: open tests/model-test.html on a laptop.

import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(import.meta.url);
const v2 = require(path.join(ROOT, 'src', 'll-assistant.js')).core;
const v1 = require(path.join(ROOT, 'tests', 'baseline', 'll-assistant.v1.js')).core;
const { checkQuestion, runQuestion } = require(path.join(ROOT, 'tests', 'check.js'));

const cat = v2.prepareCatalogue(JSON.parse(fs.readFileSync(path.join(ROOT, 'dist', 'll-assistant', 'catalogue.compact.json'), 'utf8')));
const catV1 = v1.prepareCatalogue(JSON.parse(fs.readFileSync(path.join(ROOT, 'tests', 'baseline', 'catalogue.v1.json'), 'utf8')));
const { questions } = JSON.parse(fs.readFileSync(path.join(ROOT, 'tests', 'questions.json'), 'utf8'));

const BANDS = { '4-6': [4, 6], '7-9': [7, 9], '10-12': [10, 12], '13-17': [13, 17], adult: [18, 150] };
// The old code returned age bands; turn them into a range so parseAge can be compared.
export function normaliseV1(r) {
  const bands = (r.q && r.q.ages) || [];
  const age = bands.length ? { min: Math.min(...bands.map((b) => BANDS[b][0])), max: Math.max(...bands.map((b) => BANDS[b][1])) } : null;
  return { kind: r.kind === 'ask' ? 'ask' : r.kind, askType: r.kind === 'ask' ? 'age' : null, items: (r.ids || []).map((id) => ({ id })), q: { age }, kidNote: false };
}

const short = (r) => r.kind === 'picks'
  ? r.items.map((it) => (it.ids ? `[${it.ids.map((id) => id.replace('vocab_Ladder_', '').toUpperCase()).join('·')}]` : it.id.replace(/^[a-z]+_/, '') + (it.kid ? '*' : ''))).join(', ')
  : r.kind + (r.askType ? ':' + r.askType : '');

const rows = [];
let before = 0, after = 0, total = 0;
for (const q of questions) {
  if (q.expect === 'nothing-sent') continue;
  total++;
  // The old code has no follow-ups: it gets the follow-up message on its own.
  const r1 = normaliseV1(v1.recommendRules(catV1, q.text));
  const { res: r2, shown } = await runQuestion(v2, q, (text, opts) => v2.recommendRules(cat, text, opts));
  const c1 = checkQuestion(q, r1, cat);
  const c2 = checkQuestion(q, r2, cat, shown);
  if (c1.ok) before++;
  if (c2.ok) after++;
  rows.push({ q, r1, r2, c1, c2 });
}

const esc = (s) => String(s).replace(/\|/g, '\\|');
const md = [
  '# Keyword mode: before and after',
  '',
  `Generated by \`node tests/compare.mjs\`. Before = commit fb82fd2, after = current src/. Same checker for both (tests/check.js).`,
  '',
  `**Passing: before ${before}/${total}, after ${after}/${total}.** \`*\` marks a card shown with the Kid-themed tag; [A1·A2] is one Ladder Vocabulary card with a link per level.`,
  '',
  '| # | Question | Before | After | Why before failed |',
  '|---|---|---|---|---|',
  ...rows.map((x, i) => `| ${i + 1} | ${esc(x.q.text)} | ${x.c1.ok ? '✅' : '❌'} ${esc(short(x.r1))} | ${x.c2.ok ? '✅' : '❌'} ${esc(short(x.r2))} | ${esc(x.c1.fails.join('; ') || '')}${x.c2.ok ? '' : ' · AFTER: ' + esc(x.c2.fails.join('; '))} |`),
  '',
].join('\n');

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  fs.mkdirSync(path.join(ROOT, 'tests', 'results'), { recursive: true });
  fs.writeFileSync(path.join(ROOT, 'tests', 'results', 'keyword-before-after.md'), md);
  console.log(`Keyword mode: before ${before}/${total}, after ${after}/${total}. Table: tests/results/keyword-before-after.md`);
  for (const x of rows) if (!x.c2.ok) console.log('  AFTER FAIL', x.q.id, x.c2.fails.join('; '));
  if (after !== total) process.exitCode = 1;
}
